#!/usr/bin/env node
// Writes tests/fixtures/synthetic-city-5000.json: 1 city, 50 streets × 100
// houses (5,051 nodes), NodeView-shaped, LABELLED SYNTHETIC. It is the
// performance proof for the layout and the tile mesh; it is not an engine run
// and the HUD says so when it is loaded (?source=fixture&fixture=city-5000).
//   node scripts/synth-city.ts [streets] [housesPerStreet] [seed]
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(root, 'tests/fixtures/synthetic-city-5000.json');

const STREETS = Number(process.argv[2] ?? 50);
const HOUSES = Number(process.argv[3] ?? 100);
const SEED = Number(process.argv[4] ?? 7);

// mulberry32: deterministic, no Math.random
function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(SEED);
const between = (lo: number, hi: number) => lo + (hi - lo) * rand();
const round = (x: number, d = 2) => Number(x.toFixed(d));

// ids: u64 below 2^52 (JSON-safe), unique, like the engine's minted ids
const used = new Set<number>();
function mintId(): number {
  for (;;) {
    const hi = Math.floor(rand() * 2 ** 20); // 20 bits
    const lo = Math.floor(rand() * 2 ** 32); // 32 bits
    const id = hi * 2 ** 32 + lo; // < 2^52
    if (id > 0 && !used.has(id)) { used.add(id); return id; }
  }
}
const hex64 = () => { let s = ''; while (s.length < 64) s += Math.floor(rand() * 2 ** 32).toString(16).padStart(8, '0'); return s; };

type Status = 'active' | 'waiting_at_door' | 'halted' | 'packed' | 'partitioned';
const pickStatus = (): Status => { const r = rand(); return r < 0.86 ? 'active' : r < 0.95 ? 'waiting_at_door' : 'halted'; };

interface NodeView {
  id: number; name: string; stage: 'House' | 'Street' | 'City' | 'Country' | 'World'; gate: 'House' | 'Street' | 'City' | 'Country' | 'World';
  parent: number | null; children: number; status: Status;
  compute: number; compute_allocated: number; compute_burned: number; joules_burned: number; compute_reclaimed: number;
  liquidity_belief: number; liquidity_truth: number; confidence: number; fog: number;
  generation: number; idle_ticks: number; calibrations: number; tasks_total: number; tasks_done: number; current_task: string | null;
  held: number; packed: null; note: null; burned_this_tick: number; oak_root: string; papers: number; receipts: string[];
}

function node(partial: Pick<NodeView, 'id' | 'name' | 'stage' | 'parent' | 'children'>, status: Status = 'active'): NodeView {
  const allocated = partial.stage === 'House' ? 800 : 0;
  const burned = partial.stage === 'House' ? between(0, 700) : 0;
  const phi = round(between(0.05, 1), 4);
  const waiting = status === 'waiting_at_door';
  return {
    ...partial,
    gate: 'City',
    status,
    compute: round(allocated - burned), compute_allocated: allocated, compute_burned: round(burned), joules_burned: round(burned * 0.07, 3), compute_reclaimed: 0,
    liquidity_belief: 100, liquidity_truth: 100,
    confidence: phi, fog: round(1 - phi, 4),
    generation: Math.floor(between(0, 30)), idle_ticks: waiting ? Math.floor(between(0, 4)) : 0, calibrations: Math.floor(between(0, 3)),
    tasks_total: 15, tasks_done: Math.floor(between(0, 15)), current_task: null,
    held: waiting ? 1 : 0, packed: null, note: null,
    burned_this_tick: status === 'active' && partial.stage === 'House' ? round(between(0, 45)) : 0,
    oak_root: hex64(), papers: Math.floor(between(0, 12)), receipts: [],
  };
}

const nodes: NodeView[] = [];
const cityId = mintId();
nodes.push(node({ id: cityId, name: 'Synthetic City', stage: 'City', parent: null, children: STREETS }));
for (let s = 1; s <= STREETS; s++) {
  const streetId = mintId();
  nodes.push(node({ id: streetId, name: `Synthetic Street ${s}`, stage: 'Street', parent: cityId, children: HOUSES }));
  for (let h = 1; h <= HOUSES; h++) {
    nodes.push(node({ id: mintId(), name: `S${s} House ${h}`, stage: 'House', parent: streetId, children: 0 }, pickStatus()));
  }
}
nodes.sort((a, b) => a.id - b.id); // ascending id, as the engine's BTreeMap serialises

const fixture = {
  synthetic: true,
  label: `SYNTHETIC · 1 city · ${STREETS} streets × ${HOUSES} houses · generated by scripts/synth-city.ts (seed ${SEED}), not an engine run`,
  generated_by: 'frontend/scripts/synth-city.ts',
  seed: SEED,
  streets: STREETS,
  houses_per_street: HOUSES,
  count: nodes.length,
  nodes,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(fixture));
console.log(`synth-city: ${nodes.length} nodes → ${OUT}`);
